# Generated by Django 2.0.7 on 2022-02-24 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_age', models.CharField(max_length=250, verbose_name='年龄')),
                ('i_sex', models.CharField(max_length=250, verbose_name='性别')),
                ('i_statur', models.CharField(max_length=250, verbose_name='身高')),
                ('i_weight', models.CharField(max_length=250, verbose_name='体重')),
                ('i_systolicpress', models.CharField(max_length=250, verbose_name='收缩压')),
                ('i_diastolicpress', models.CharField(max_length=250, verbose_name='舒张压')),
                ('i_bloodglucose', models.CharField(max_length=250, verbose_name='血糖')),
                ('i_smoke', models.CharField(max_length=250, verbose_name='是否吸烟')),
                ('i_drink', models.CharField(max_length=250, verbose_name='是否饮酒')),
                ('i_sport', models.CharField(max_length=250, verbose_name='是否运动')),
            ],
            options={
                'verbose_name': '健康信息',
                'verbose_name_plural': '健康信息',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('u_logo', models.FileField(default='default.jpg', upload_to='images', verbose_name='用户头像')),
                ('u_pwd', models.CharField(max_length=40, verbose_name='用户密码')),
                ('u_email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('u_realname', models.CharField(default='', max_length=20, verbose_name='真实姓名')),
                ('u_address', models.CharField(default='', max_length=100, verbose_name='地址')),
                ('u_postcode', models.CharField(default='', max_length=6, verbose_name='邮编')),
                ('u_phone', models.CharField(default='', max_length=11, verbose_name='手机号')),
                ('u_name_passOrfail', models.BooleanField(default=True, verbose_name='允许登录')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
        migrations.AddField(
            model_name='healthinformation',
            name='i_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo', verbose_name='消息'),
        ),
    ]
