# Generated by Django 2.0.7 on 2022-02-24 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthinformation',
            name='i_cholesterol',
            field=models.CharField(default='0', max_length=250, verbose_name='胆固醇'),
        ),
        migrations.AddField(
            model_name='healthinformation',
            name='i_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='输入时间'),
        ),
        migrations.AlterField(
            model_name='healthinformation',
            name='i_bloodglucose',
            field=models.CharField(default='0', max_length=250, verbose_name='血糖'),
        ),
    ]
