# Generated by Django 2.0.7 on 2022-02-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20220224_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthinformation',
            name='i_age',
            field=models.IntegerField(default='0', max_length=250, verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='healthinformation',
            name='i_bloodglucose',
            field=models.FloatField(default='0', max_length=250, verbose_name='bloodglucose'),
        ),
        migrations.AlterField(
            model_name='healthinformation',
            name='i_cholesterol',
            field=models.FloatField(default='0', max_length=250, verbose_name='holesterol'),
        ),
        migrations.AlterField(
            model_name='healthinformation',
            name='i_diastolicpress',
            field=models.FloatField(default='0', max_length=250, verbose_name='iastolicpress'),
        ),
        migrations.AlterField(
            model_name='healthinformation',
            name='i_drink',
            field=models.IntegerField(default='0', max_length=250, verbose_name='drink'),
        ),
        migrations.AlterField(
            model_name='healthinformation',
            name='i_sex',
            field=models.IntegerField(default='0', max_length=250, verbose_name='sex'),
        ),
        migrations.AlterField(
            model_name='healthinformation',
            name='i_smoke',
            field=models.IntegerField(default='0', max_length=250, verbose_name='smoke'),
        ),
        migrations.AlterField(
            model_name='healthinformation',
            name='i_sport',
            field=models.IntegerField(default='0', max_length=250, verbose_name='sport'),
        ),
        migrations.AlterField(
            model_name='healthinformation',
            name='i_statur',
            field=models.FloatField(default='0', max_length=250, verbose_name='height'),
        ),
        migrations.AlterField(
            model_name='healthinformation',
            name='i_systolicpress',
            field=models.FloatField(default='0', max_length=250, verbose_name='systolicpress'),
        ),
        migrations.AlterField(
            model_name='healthinformation',
            name='i_weight',
            field=models.FloatField(default='0', max_length=250, verbose_name='weight'),
        ),
    ]
