# Generated by Django 2.0.7 on 2022-02-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20220225_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthinformation',
            name='i_age',
            field=models.IntegerField(default='0', verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='healthinformation',
            name='i_drink',
            field=models.IntegerField(default='0', verbose_name='drink'),
        ),
        migrations.AlterField(
            model_name='healthinformation',
            name='i_sex',
            field=models.IntegerField(default='0', verbose_name='sex'),
        ),
        migrations.AlterField(
            model_name='healthinformation',
            name='i_smoke',
            field=models.IntegerField(default='0', verbose_name='smoke'),
        ),
        migrations.AlterField(
            model_name='healthinformation',
            name='i_sport',
            field=models.IntegerField(default='0', verbose_name='sport'),
        ),
    ]
