# Generated by Django 2.0.7 on 2022-02-25 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20220225_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='u_logo',
        ),
    ]
